name: bn-data-collectors package build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: bundle install

      - name: Build gem
        run: gem build *.gemspec

      - name: Push gem
        run: |
          pwd
          ls -la
          filename=$(ls *.gem | head -n 1)
          gem push "$filename"